package example2;


/**
* example2/AFactoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sr.idl
* Tuesday, April 29, 2014 12:10:44 PM CEST
*/

public interface AFactoryOperations 
{
  example2.Item create_item (String name, String type) throws example2.ItemAlreadyExists;
  example2.Item take_item (String name) throws example2.ItemNotExists, example2.ItemBusy;
  void release_item (String name) throws example2.ItemNotExists;
} // interface AFactoryOperations
