package example2;


/**
* example2/ItemA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sr.idl
* Tuesday, April 29, 2014 12:10:44 PM CEST
*/

public interface ItemA extends ItemAOperations, example2.Item, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItemA
