package example2;

/**
* example2/ItemHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sr.idl
* Tuesday, April 29, 2014 12:10:44 PM CEST
*/

public final class ItemHolder implements org.omg.CORBA.portable.Streamable
{
  public example2.Item value = null;

  public ItemHolder ()
  {
  }

  public ItemHolder (example2.Item initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = example2.ItemHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    example2.ItemHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return example2.ItemHelper.type ();
  }

}
