package example2;


/**
* example2/ItemBusy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sr.idl
* Tuesday, April 29, 2014 12:10:44 PM CEST
*/

public final class ItemBusy extends org.omg.CORBA.UserException
{

  public ItemBusy ()
  {
    super(ItemBusyHelper.id());
  } // ctor


  public ItemBusy (String $reason)
  {
    super(ItemBusyHelper.id() + "  " + $reason);
  } // ctor

} // class ItemBusy
